# Generated by Django 4.2 on 2024-04-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0008_alter_alamatpengiriman_options_payment_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('S', 'Sport'), ('C', 'Casual'), ('F', 'Formal')], max_length=2),
        ),
    ]
